### ISSUE TITLE
CCDA to FHIR Conversion - Does Not work in Deployed Jar

### ISSUE THREAD

**Issue by balanscott** [Project-Herophilus/iDaaS-Connect#22]
**Describe the bug**
The CCDA to FHIR conversion does not work consistently

**To Reproduce**
1. Run the jar based compiled artifact and send in a CCDA via Postman, it fails
2. Start up a command line and start with mvn spring-boot: run and send in a CCDA via Postman, it works.

**Expected behavior**
CCDA to FHIR conversion should work in the compiled artifact the same as in the mvn spring-boot:run artifact

**Comment by GuilhermeCamposo** [comment]
@balanscott I could not reproduce the error. Could you share the error log you are seeing? Which version of java are you using?
