### ISSUE TITLE
Cloud Native Migration and Enhancement of iDaaS Connect Third Party

### ISSUE THREAD

**Issue by balanscott** [Project-Herophilus/iDaaS-Connect#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GuilhermeCamposo** [comment]
@balanscott  About data format, we could standardize things using https://cloudevents.io/ . Specs: https://github.com/cloudevents/spec
