### ISSUE TITLE
Feature: Enhance Third Party

### ISSUE THREAD

**Issue by balanscott** [Project-Herophilus/iDaaS-Connect#48]
**Problem:**
We need to be able to filter specific SFTP to only process HL7-based files.

**Potential Solution:**
Let's apply a file name filter for ANY files with the .dat and .hl7 extensions. 

**Potential Alternatives:**
N/A

**Additional Details:**
N/A

**Comment by GuilhermeCamposo** [comment]
@balanscott filter added and deployed. Just to let you know since we are not merging at this point
